# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ag-magic-wordle

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Create .env file and build
        env:
          AZURE_STORAGE_TABLE_SAS_TOKEN: ${{ secrets.AZURESASTOKEN }}
        run: |
          echo "AZURE_STORAGE_TABLE_SAS_TOKEN=${{ secrets.AZURESASTOKEN }}" > production.env
          echo "cat production.env"
          cat production.env
          echo "ls -force ."
          ls -force .
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test --if-present
      
      - name: create React web.config
        run: |
           echo '<?xml version="1.0"?>' > ./build/web.config
           echo '<configuration>' >> ./build/web.config
           echo '<system.webServer>' >> ./build/web.config
           echo '<rewrite>' >> ./build/web.config
           echo '<rules>' >> ./build/web.config
           echo '<rule name="React Routes" stopProcessing="true">' >> ./build/web.config
           echo '<match url=".*" />' >> ./build/web.config
           echo '<conditions logicalGrouping="MatchAll">' >> ./build/web.config
           echo '<add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />' >> ./build/web.config
           echo '<add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />' >> ./build/web.config
           echo '<add input="{REQUEST_URI}" pattern="^/(api)" negate="true" />' >> ./build/web.config
           echo '</conditions>' >> ./build/web.config
           echo '<action type="Rewrite" url="/" />' >> ./build/web.config
           echo '</rule>' >> ./build/web.config
           echo '</rules>' >> ./build/web.config
           echo '</rewrite>' >> ./build/web.config
           echo '</system.webServer>' >> ./build/web.config
           echo '</configuration>' >> ./build/web.config
           echo 'cat ./build/web.config'
           cat ./build/web.config
           echo "ls -force -r ./build"
           ls -force -r ./build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ./build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ag-magic-wordle'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E230E641262B4C3BAEB6B9A82D385D4A }}
          package: .
